Add, Subtract, Multiply Many
Rhymond/go-money pull request #117
Opened 2022-08-09 20:07 UTC by AyoobMH

* **Please check if the PR fulfills these requirements**
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
 Addition, subtraction, and multiplication can only be done with single values.

* **What is the new behavior (if this is a feature change)?**
 Addition, subtraction, and multiplication using many values.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
NO

* **Other information**:
 * Fixes #74 
 * Credit to @SepehrAsh for opening #78 ,but it got closed.

2022-08-10 11:00 UTC, Rhymond commented
Hi @AyoobMH 

Thanks for the PR! I was just thinking, maybe we can update original methods to accept variadic parameters instead?
```
func (m *Money) Add(om ...*Money) (*Money, error)
```

In that way the functionality to add multiple would exists and it would not introduce any breaking changes. Of course, I would expect to do a sanity check `if len(om) != 0` and return error before applying operation.

What do you think?

2022-08-10 11:50 UTC, AyoobMH commented
Hi @Rhymond, thanks for your efforts.
I think updating original methods to have variadic parameters is even better, it wouldn't introduce any redundant code. Are you thinking of updating only `Add`, `Subtract`, `Multiply`? I would be happy to open another PR for that.

2022-08-10 13:23 UTC, Rhymond commented
> Hi @Rhymond, thanks for your efforts.
> 
> I think updating original methods to have variadic parameters is even better, it wouldn't introduce any redundant code. Are you thinking of updating only `Add`, `Subtract`, `Multiply`? I would be happy to open another PR for that.

Exactly! Yes `Add`, `Subtract` and `Multiply`. Appreciate your time 🙏

2022-08-10 17:58 UTC, AyoobMH commented
Hi @Rhymond 

I have modified the PR and added variadic parameters. For checking parameters, I have used panic instead of an error, I believe not passing any parameter is considered a bad use of the package and should not happen during runtime. What do you think?

2022-08-18 13:45 UTC, totemcaf requested changes

2022-08-18 13:45 UTC, totemcaf commented on money.go
> +		panic("At least one Money is required to add")
I think you can return the original value instead of panic because it is not incorrect mathematically.

2022-08-18 13:45 UTC, totemcaf commented on money.go
> +
You can use the alternative form:
```suggestion
	for _, m2:= range om {
		if err := m.assertSameCurrency(m2); err != nil {
			return nil, err
		}

		k.amount = mutate.calc.add(k.amount, m2.amount)
	}

```

2022-08-18 13:45 UTC, totemcaf commented on money.go
> +func (m *Money) Add(om ...*Money) (*Money, error) {
It's typically to add an "s" to the name to denote an array of:
```suggestion
func (m *Money) Add(ms ...*Money) (*Money, error) {
```

2022-08-18 13:45 UTC, totemcaf commented on money.go
> +		panic("At least one Money is required to subtract")
Same for add, you can return original value instead of panicking.

2022-08-18 13:45 UTC, totemcaf commented on money.go
> +		panic("At least one multiplier is required to multiply")
Here is more controversial to return the original value, so I think it is ok to panic

2022-08-19 16:30 UTC, AyoobMH commented
@totemcaf Thanks for the review, the requested changes were made!

2022-11-14 12:22 UTC, AyoobMH commented
Hi @Rhymond @totemcaf , this PR is ready for review, would appreciate your review, thanks in advance!

2024-05-16 08:52 UTC, AyoobMH commented
Hi @Rhymond, any updated for this PR, thanks in advance!

2024-07-29 06:19 UTC, Rhymond approved these changes
Sorry for late response, LGTM

2024-07-29 06:19 UTC, merged